version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongPass123!"
      ACCEPT_EULA: "Y"
    restart: always

  peopleapi:
    build:
      context: ./PeopleApi
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command:  >
      /bin/bash -c "
        /wait-for-it.sh mssql:1433 -- dotnet ef database update &&
        dotnet PeopleApi.dll
      "

  identityapi:
    build:
      context: ./IdentityApi
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: >
      /bin/bash -c "
        /wait-for-it.sh mssql:1433 -- dotnet ef database update && 
        dotnet IdentityApi.dll
      "

  postapi:
    build:
      context: ./PostApi
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: >
      /bin/bash -c "
        /wait-for-it.sh mssql:1433 -- dotnet ef database update && 
        dotnet PostApi.dll
      "

  socialmediaapp:
    build:
      context: ./SocialMediaApp
      dockerfile: Dockerfile
    depends_on:
      - identityapi
      - postapi
      - peopleapi
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
